# Generated by Django 4.1.3 on 2023-10-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="payment_period",
            field=models.FloatField(),
        ),
    ]
