# Generated by Django 4.1.3 on 2023-10-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0028_auto_20180530_0934"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="subscription_period",
            field=models.CharField(
                choices=[
                    ("0.25", "Quarter Month"),
                    ("0.5", "Half Month"),
                    ("1", "1 Month"),
                    ("2", "2 Months"),
                    ("3", "3 Months"),
                    ("4", "4 Months"),
                    ("5", "5 Months"),
                    ("6", "6 Months"),
                    ("7", "7 Months"),
                    ("8", "8 Months"),
                    ("9", "9 Months"),
                    ("10", "10 Months"),
                    ("11", "11 Months"),
                    ("12", "12 Months"),
                ],
                default="1",
                max_length=30,
                verbose_name="Subscription Period",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="subscription_type",
            field=models.CharField(
                choices=[("gym", "Gym"), ("pt", "Personal Training")],
                default="gym",
                max_length=30,
                verbose_name="Subscription Type",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="unique_member_id",
            field=models.CharField(max_length=50, verbose_name="MEMBER's GYM ID"),
        ),
    ]
