# Generated by Django 4.1.3 on 2023-10-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0029_alter_member_subscription_period_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="weight",
            field=models.CharField(default=0, max_length=3, verbose_name="Last Name"),
            preserve_default=False,
        ),
    ]
